---

  - name: create ssl directory      
    file:
      path: "{{ item }}"
      state: directory
      group: vault
    loop:
      - "{{ ssl_path }}"
      - "{{ ssl_path }}/private"
      - "{{ ssl_path }}/certs"

  - name: Remove old SSL Certificate
    file:
      path: "{{ ssl_path}}/private/vault-selfsigned.key"
      state: absent
    tags:
      - sslrenew

  - name: Check if SSL Certificate Exist
    stat: 
      path: "/{{ ssl_path }}/private/vault-selfsigned.key"
    register: ssl_cert

  - name: Copy ssl configuration file
    template: 
      src: vault.cnf.j2 
      dest: "/{{ ssl_path }}/vault.cnf" 
      mode: 0644
    when: ssl_cert.stat.exists == False

  - name: Generate Private Key
    command: openssl genrsa -out "{{ ssl_path }}/private/vault-selfsigned.key" 2048
    when: ssl_cert.stat.exists == False

  - name: Create CSR
    command: openssl req -subj "/C=DE/ST=NRW, Inc./CN={{ inventory_hostname }}"  -new -out "{{ ssl_path }}/private/vault-selfsigned.csr" -key "{{ ssl_path }}/private/vault-selfsigned.key" -config "{{ ssl_path }}/vault.cnf"
    when: ssl_cert.stat.exists == False

  - name: Dump Certificate
    command: openssl req -text -noout -in "{{ ssl_path }}/private/vault-selfsigned.csr"
    register: dump_csr

  - debug:
      var: dump_csr

  - name: Self Sign Certificate
    command: openssl x509 -req -days 3650 -in "{{ ssl_path }}/private/vault-selfsigned.csr" -signkey "{{ ssl_path }}/private/vault-selfsigned.key" -out "{{ ssl_path }}/certs/vault-selfsigned.crt" -extensions v3_req -extfile "{{ ssl_path }}/vault.cnf"
    when: ssl_cert.stat.exists == False

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: "{{ item }}"
      owner: root
      mode: 0640
      group: vault
    loop:
      - "{{ ssl_path }}/private/vault-selfsigned.key"
      - "{{ ssl_path }}/certs/vault-selfsigned.crt"

  - name: Restart vault service
    systemd:
      state: restarted
      name: vault
      daemon_reload: yes



