---
- name: Install and Configure Vault
  become: yes
  hosts: vault
  roles:
    - role: vault
      tags:
        - vault
    - role: ssl
      tags:
        - ssl
        - sslrenew
    # - role: ufw_rules
    #   tags:
    #     - ufw
